// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MiddlewareUIClient is the client API for MiddlewareUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiddlewareUIClient interface {
	// ListEngineSpecs returns a list of Middleware Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MiddlewareUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type middlewareUIClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddlewareUIClient(cc grpc.ClientConnInterface) MiddlewareUIClient {
	return &middlewareUIClient{cc}
}

func (c *middlewareUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MiddlewareUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MiddlewareUI_ServiceDesc.Streams[0], "/v1.MiddlewareUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &middlewareUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MiddlewareUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type middlewareUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *middlewareUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *middlewareUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.MiddlewareUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareUIServer is the server API for MiddlewareUI service.
// All implementations must embed UnimplementedMiddlewareUIServer
// for forward compatibility
type MiddlewareUIServer interface {
	// ListEngineSpecs returns a list of Middleware Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, MiddlewareUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedMiddlewareUIServer()
}

// UnimplementedMiddlewareUIServer must be embedded to have forward compatible implementations.
type UnimplementedMiddlewareUIServer struct {
}

func (UnimplementedMiddlewareUIServer) ListEngineSpecs(*ListEngineSpecsRequest, MiddlewareUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedMiddlewareUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedMiddlewareUIServer) mustEmbedUnimplementedMiddlewareUIServer() {}

// UnsafeMiddlewareUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddlewareUIServer will
// result in compilation errors.
type UnsafeMiddlewareUIServer interface {
	mustEmbedUnimplementedMiddlewareUIServer()
}

func RegisterMiddlewareUIServer(s grpc.ServiceRegistrar, srv MiddlewareUIServer) {
	s.RegisterService(&MiddlewareUI_ServiceDesc, srv)
}

func _MiddlewareUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MiddlewareUIServer).ListEngineSpecs(m, &middlewareUIListEngineSpecsServer{stream})
}

type MiddlewareUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type middlewareUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *middlewareUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MiddlewareUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MiddlewareUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MiddlewareUI_ServiceDesc is the grpc.ServiceDesc for MiddlewareUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiddlewareUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MiddlewareUI",
	HandlerType: (*MiddlewareUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _MiddlewareUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _MiddlewareUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "middleware-ui.proto",
}
